version: '3.0'

services:
  selenium:
    image: selenium/standalone-firefox:3.12.0-americium      
    logging:
      driver: "none"
      
  frontend:     
    build: ../frontend/ 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 5s
      retries: 3   
    ports: 
    - 8080:80
    
  wdio:
    container_name: wdio-e2e
    build: .  
    depends_on:      
      - selenium
      - frontend
    environment:
      - HOST=selenium
    command: npm test 
    volumes:
      - ./errorShots:/usr/src/app/errorShots

